### ISSUE TITLE
User Story 1: List Of Items

### ISSUE THREAD

**Issue by e-rmkt** [e-rmkt/wishlist#3]
## Value proposition

`As a` user
`I want to` see all of my noted items
`so that` I can easily scan relevant information about my items

## Description

<img width="269" alt="US1" src="https://github.com/e-rmkt/wishlist/assets/140353817/423c6b93-240d-4b52-8aae-ea34e7535f25">

## Acceptance criteria

- [ ] On the homepage, there is a list of items displayed
    - [ ] The list has two columns
    - [ ] The list is vertically scrollable
- [ ] Each item in the list includes the following details:
    - [ ] an image
    - [ ] the name/title of the item
    - [ ] the price
    - [ ] the article number
- [ ] If there is an issue loading the trip data from the source, an error
  message is displayed to the user
- [ ]  There is a headline at the top left corner

## Tasks

- [ ] Create the collection "Items" in MongoDB with the mock data
- [ ] Create the feature branch 'feat/item-list'
- [ ] Fetch a list of your items from the MongoDB collection in the index.js
    - [ ] Implement the error handling logic to display an error message if 
      there is an issue loading the item data from the collection
- [ ] Create the component `ItemCard`, which renders: 
    - [ ] an image
    - [ ] the name/title of the item
    - [ ] the price
    - [ ] the article number, if given
- [ ] Create the component `ItemList`
    - [ ] map through the fetched list of items and render the `ItemCard` component
      for each item
- [ ] In the index.js:
    - [ ] render a `<h1> element `for the page title
    - [ ] render the 'ItemList' component 

<h3> Schema </h3>

```
const Item = 
{ 
  name: { type: String, required: true },
  img: { type: String },
  product_id: { type: String },
  price: { type: String, required: true },
  link: { type: String }
  collections:  [ { type: String } ] ,
};
```
<h3> Datenmodell </h3>

```
[
{
name: "Rhode Peptide Lip Treatment",
img: "https://assets.glamour.de/photos/65144854252b3738b202a7d7/2:3/w_3140,h_4710,c_limit/270923-Rhode-Launch-Aufmacher.jpg",
product_id: "",
price: "$16.00",
link: "https://www.rhodeskin.com/products/peptide-lip-treatment",
collections: ["wishlist", "skincare"],
},
{
name: "Prada Re-Edition 2005 Mini Bag aus Re-Nylon",
img: "https://hips.hearstapps.com/hmg-prod/images/prada-nylon-bags-1657206588.jpg?crop=0.8893229166666666xw:1xh;center,top&resize=768:*",
product_id: "1NE204_R064_F0002",
price: "1344 €",
link: "https://www.prada.com/at/de/p/prada-re-edition-2005-mini-bag-aus-re-nylon/1NE204_R064_F0002",
collections: ["wishlist", "old money"],
}
]
```
