### ISSUE TITLE
User Story 2: Add A New Item

### ISSUE THREAD

**Issue by e-rmkt** [e-rmkt/wishlist#4]
## Value proposition

`As a` user
`I want to` be able to create and add new items to my note collection,
`so that` I can capture my shopping experience seamlessly.

## Description

<img width="513" alt="US2" src="https://github.com/e-rmkt/wishlist/assets/140353817/667a4d3a-9e47-41c3-a08a-31f83ff49cf7">

## Acceptance criteria

- [ ] On the homepage is a button that opens a form
     - [ ] if there is no trip planned, the following message will be displayed in the center of the display "Create your first trip!" 
            with a button beneath
     - [ ] if there are already trips planned, the button will be found in the center of the bottom of the display
- [ ]  The form contains the following input fields/elements:
     - [ ]
- [ ] If the user clicks on the cancel button, the form will be closed and the user will be redirected to the homepage
- [ ] If the user clicks on the create button, the form will be closed, the user will be redirected to the homepage and the newly 
       created trip will be shown in the list
- [ ] The user can't submit an empty form, if the user tries to submit an empty form, he receives the default message of the form element which fields are required
    

## Tasks

- [ ] Create a feature branch 'create-trip'
- [ ] Create a 'CreateTrip' component that contains a link (styled as a button)
- [ ] Create the 'TripForm' page `pages/forms/TripForm/index.js` that renders a form element which contains the following input fields/elements: 
     - [ ] 
- [ ] Create a 'CreateButton' component 
   - [ ] By clicking the button, the trip will be created and the user will be redirected to the index.js (use Mongoose)
      - [ ] Define a `POST`  API route
      - [ ] Connect a handler function which uses this API route
- [ ] Create a 'CancelButton' component, which is a link styled as a button
     - [ ] By clicking the link, the user will be redirected to the index.js and the data will not be saved
- [ ] Update the index.js
     - [ ] render the 'CreateTrip' component
- [ ]  Update the 'CreateTrip' component to navigate to the 'TripForm' page
